<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.villseriol</groupId>
  <artifactId>osmosis-transliterate-parent</artifactId>
  <packaging>pom</packaging>
  <version>2.0.1</version>

  <name>osmosis-transliterate-parent</name>
  <description>Osmosis plugin for transliterating Japanese to Basic Latin.</description>
  <inceptionYear>2026</inceptionYear>
  <url>https://github.com/villseriol/osmosis-transliterate</url>
  <organization>
    <name>Villseriol</name>
    <url>https://www.villseriol.org</url>
  </organization>
  <developers>
    <developer>
      <id>EY4180</id>
      <name>EY4180</name>
      <email>ey4180@villseriol.org</email>
    </developer>
  </developers>

  <licenses>
    <license>
      <name>GNU General Public License v3.0</name>
      <url>https://www.gnu.org/licenses/gpl-3.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <modules>
    <module>osmosis-transliterate</module>
    <module>osmosis-transliterate-reports</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <osmosis.version>0.48.3</osmosis.version>
    <jackson.version>3.1.3</jackson.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.github.villseriol</groupId>
        <artifactId>osmosis-transliterate</artifactId>
        <version>${project.version}</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.openstreetmap.osmosis/osmosis-core -->
      <dependency>
        <groupId>org.openstreetmap.osmosis</groupId>
        <artifactId>osmosis-core</artifactId>
        <version>${osmosis.version}</version>
      </dependency>

      <!-- Source: https://central.sonatype.com/artifact/io.github.villseriol/kakasi2 -->
      <dependency>
        <groupId>io.github.villseriol</groupId>
        <artifactId>kakasi2</artifactId>
        <version>2.0.2</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-core -->
      <dependency>
        <groupId>tools.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>${jackson.version}</version>
      </dependency>

      <!-- Source:
      https://mvnrepository.com/artifact/tools.jackson.dataformat/jackson-dataformat-xml -->
      <dependency>
        <groupId>tools.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-xml</artifactId>
        <version>${jackson.version}</version>
      </dependency>

      <!-- Source:
      https://mvnrepository.com/artifact/tools.jackson.dataformat/jackson-dataformat-yaml -->
      <dependency>
        <groupId>tools.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-yaml</artifactId>
        <version>${jackson.version}</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/com.ibm.icu/icu4j -->
      <dependency>
        <groupId>com.ibm.icu</groupId>
        <artifactId>icu4j</artifactId>
        <version>78.3</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-text -->
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-text</artifactId>
        <version>1.15.0</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-csv -->
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-csv</artifactId>
        <version>1.14.1</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.openstreetmap.osmosis/osmosis-testutil -->
      <dependency>
        <groupId>org.openstreetmap.osmosis</groupId>
        <artifactId>osmosis-testutil</artifactId>
        <version>${osmosis.version}</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.openstreetmap.osmosis/osmosis-xml -->
      <dependency>
        <groupId>org.openstreetmap.osmosis</groupId>
        <artifactId>osmosis-xml</artifactId>
        <version>${osmosis.version}</version>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/junit/junit -->
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.5.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.3.0</version>
          <configuration>
            <argLine>-Dfile.encoding=UTF-8</argLine>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.4.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.12.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.6.1</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>3.6.3</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>3.6.0</version>

        <configuration>
          <configLocation>${maven.multiModuleProjectDirectory}/checkstyle.xml</configLocation>
          <encoding>UTF-8</encoding>
          <consoleOutput>true</consoleOutput>
          <failsOnError>true</failsOnError>
        </configuration>

        <executions>
          <execution>
            <id>checkstyle-validation</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>