name: Deploy Package
on:
  push:
    tags:
      - '*.*.*'
  workflow_run:
    workflows: ['Create Tag']
    types:
      - completed
permissions:
  contents: write
jobs:
  package-artifacts:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-id: central
          gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Package & Sign
        env:
          MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
        run: mvn clean verify
      - name: Get Final Artifact Names
        id: get-final-name
        run: |
          FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)

          echo "final_name=$FINAL_NAME" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: osmosis-kakasi-artifacts
          path: |
            target/${{ steps.get-final-name.outputs.final_name }}.jar
            target/${{ steps.get-final-name.outputs.final_name }}-sources.jar
            target/${{ steps.get-final-name.outputs.final_name }}-javadoc.jar
            target/${{ steps.get-final-name.outputs.final_name }}-plugin.zip

  create-release:
    runs-on: ubuntu-latest
    needs: package-artifacts
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: osmosis-kakasi-artifacts
          path: artifacts
      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/*.jar
            artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
