name: Package Artifacts
on: [workflow_dispatch]
jobs:
  package-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          server-id: central
          gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Package
        env:
          MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
        run: mvn clean package
      - name: Get Final Artifact Names
        id: get-final-name
        run: |
          FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)

          echo "final_name=$FINAL_NAME" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: osmosis-kakasi-artifacts
          path: |
            target/${{ steps.get-final-name.outputs.final_name }}.jar
            target/${{ steps.get-final-name.outputs.final_name }}-sources.jar
            target/${{ steps.get-final-name.outputs.final_name }}-javadoc.jar
            target/${{ steps.get-final-name.outputs.final_name }}-plugin.zip
